### ISSUE TITLE
OSMgadget link to (JOSM )

### ISSUE THREAD

**Issue by katpatuka** [bjohas/OSM-Wikipedia-Monkey#1]
I'd rather prefer the link to the object itself using /load_object instead of downloading a bounding box for the josm-link...

... aber insgesamt bravo! OSMgadget ist ne gute idee! ;)

**Comment by bjohas** [comment]
HI @katpatuka - danke!

if the gadget finds a match, it will not download the bounding box. It works like this: On load, the script fetches the coords/WD from the wiki page, and offers an OSM/JOSM link for the bounding box.

It then asynchronously does an overpass search based on wiki title (search OSM for "wikipedia=") and WD (search OSM for "wikidata="). If a match is found, the OSM/JOSM links are replaced by edit/load links for the found OSM object. If several matches are found, additional links to those objects are appended.

I'll add this to the documentation!

Hoffe das macht Sinn!

**Comment by katpatuka** [comment]
I had tested it with https://en.wikipedia.org/wiki/Hacıbektaş :

- (OSM/node95606756) uses node http://www.openstreetmap.org/node/95606756?zoom=18&mlat=38.950&mlon=34.567 while
- (JOSM) uses http://127.0.0.1:8111/load_and_zoom?right=34.572&left=34.562&top=38.955000000000005&bottom=38.945&new_layer=false&select=node95606756

So I thought josm could just get`/node/95606756` ...

**Comment by bjohas** [comment]
You are absolutely right - sorry. I'll amend it so that without OSM object, the area is loaded, but with OSM object, only the object is loaded. The iD link also isn't quite correct.

**Comment by bjohas** [comment]
This is now fixed. Where links have been rewritten from area->object, a "+" is added. (Clearly the whole UI is not great, but I thought some kind of indication that the link has changed would be god).
